version: '3.3'

services:
  web:
    build :
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/GoldBoost/static
      - media_volume:/usr/src/GoldBoost/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    volumes:
      - .:/usr/src/GoldBoost/web
    command: celery -A config worker -l info
    depends_on:
      - db
      - redis
      - web
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/GoldBoost/static
      - media_volume:/usr/src/GoldBoost/media
    ports:
      - "8150:80"
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
