# Generated by Django 5.0.2 on 2024-02-26 21:03

import django.db.models.deletion
import meta.models
import src.website.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Calendars',
                'verbose_name_plural': 'Calendars',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to=src.website.utils.get_timestamp_path)),
            ],
            options={
                'verbose_name': 'Games',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tab',
                'verbose_name_plural': 'Tabs',
            },
        ),
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team1_img', models.ImageField(upload_to='')),
                ('team1_from', models.TimeField()),
                ('team1_until', models.TimeField()),
                ('team2_img', models.ImageField(upload_to='')),
                ('team2_from', models.TimeField()),
                ('team2_until', models.TimeField()),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='games.catalogpage')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_pages', related_query_name='game', to='games.game')),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='tab_content', to='games.tab')),
            ],
            options={
                'verbose_name': 'Catalog Page',
                'verbose_name_plural': 'Catalog Pages',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.AddField(
            model_name='calendar',
            name='catalog_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.catalogpage'),
        ),
        migrations.CreateModel(
            name='TabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.TextField()),
                ('tab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='games.tab')),
            ],
            options={
                'verbose_name': 'Tab Item',
                'verbose_name_plural': 'Tab Items',
            },
        ),
        migrations.CreateModel(
            name='WorthLookCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=src.website.utils.get_timestamp_path)),
                ('title', models.CharField()),
                ('link', models.URLField()),
                ('catalog_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worth_items', to='games.catalogpage')),
            ],
            options={
                'verbose_name': 'Worth look carousel',
                'verbose_name_plural': 'Worth look carousel',
            },
        ),
    ]
