# Generated by Django 5.0.2 on 2024-03-13 14:48

import django.db.models.deletion
import meta.models
import src.products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
                'db_table': 'calendars',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_filter', models.ImageField(null=True, upload_to=src.products.utils.get_timestamp_path)),
                ('logo_product', models.ImageField(null=True, upload_to=src.products.utils.get_timestamp_path)),
                ('logo_filter_alt', models.CharField(max_length=255, null=True)),
                ('logo_product_alt', models.CharField(max_length=255, null=True)),
                ('order', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Games',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tab',
                'verbose_name_plural': 'Tabs',
                'db_table': 'tabs',
            },
        ),
        migrations.CreateModel(
            name='WorthLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Worth look',
                'verbose_name_plural': 'Worth look',
                'db_table': 'worth_look',
            },
        ),
        migrations.CreateModel(
            name='CalendarBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.calendar')),
            ],
            options={
                'verbose_name': 'Calendar Block',
                'verbose_name_plural': 'Calendar Blocks',
                'db_table': 'calendar_blocks',
            },
        ),
        migrations.CreateModel(
            name='CalendarBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team1_img', models.ImageField(upload_to='')),
                ('team1_img_alt', models.CharField(max_length=255, null=True)),
                ('team1_from', models.TimeField()),
                ('team1_until', models.TimeField()),
                ('team2_img', models.ImageField(upload_to='')),
                ('team2_img_alt', models.CharField(max_length=255, null=True)),
                ('team2_from', models.TimeField()),
                ('team2_until', models.TimeField()),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.calendarblock')),
            ],
            options={
                'db_table': 'calendar_block_items',
            },
        ),
        migrations.CreateModel(
            name='TabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(null=True)),
                ('tab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab_items', to='games.tab')),
            ],
            options={
                'verbose_name': 'Tab Item',
                'verbose_name_plural': 'Tab Items',
                'db_table': 'tab_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.calendar')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='games.catalogpage')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_pages', related_query_name='game', to='games.game')),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.tab')),
                ('worth_look', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.worthlook')),
            ],
            options={
                'verbose_name': 'Catalog Page',
                'verbose_name_plural': 'Catalog Pages',
                'db_table': 'catalog_pages',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='WorthLookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=src.products.utils.get_timestamp_path)),
                ('image_alt', models.CharField(max_length=255, null=True)),
                ('carousel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.worthlook')),
                ('catalog_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.catalogpage')),
            ],
            options={
                'verbose_name': 'Worth look item',
                'verbose_name_plural': 'Worth look items',
                'db_table': 'worth_look_items',
            },
        ),
    ]
