# Generated by Django 5.0.2 on 2024-04-09 13:23

import src.products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_img',
            field=models.ImageField(null=True, upload_to=src.products.utils.get_timestamp_path),
        ),
    ]
