# Generated by Django 5.0.2 on 2024-02-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='catalog_page',
        ),
        migrations.AddField(
            model_name='catalogpage',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.calendar'),
        ),
    ]
