# Generated by Django 5.0.2 on 2024-04-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_team_team_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogpage',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
