# Generated by Django 5.0.2 on 2024-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_catalogpage_options_catalogpage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
