# -*- coding: utf-8 -*-
# Generated by Django 5.0.2 on 2024-04-01 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_game_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calendarblock",
            old_name="subtitle_ua",
            new_name="subtitle_uk",
        ),
        migrations.RenameField(
            model_name="calendarblock",
            old_name="title_ua",
            new_name="title_uk",
        ),
        migrations.RenameField(
            model_name="catalogpage",
            old_name="description_ua",
            new_name="description_uk",
        ),
        migrations.RenameField(
            model_name="catalogpage",
            old_name="title_ua",
            new_name="title_uk",
        ),
        migrations.RenameField(
            model_name="catalogtabs",
            old_name="content_ua",
            new_name="content_uk",
        ),
        migrations.RenameField(
            model_name="catalogtabs",
            old_name="title_ua",
            new_name="title_uk",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="logo_filter_alt_ua",
            new_name="logo_filter_alt_uk",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="logo_product_alt_ua",
            new_name="logo_product_alt_uk",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="team_img_alt_ua",
            new_name="team_img_alt_uk",
        ),
        migrations.RenameField(
            model_name="worthlookitem",
            old_name="image_alt_ua",
            new_name="image_alt_uk",
        ),
    ]
