# Generated by Django 5.0.2 on 2024-03-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_tab_title'),
        ('products', '0004_alter_producttabs_options_remove_product_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogpage',
            name='tab',
        ),
        migrations.DeleteModel(
            name='TabItem',
        ),
        migrations.DeleteModel(
            name='Tab',
        ),
    ]
