# Generated by Django 5.0.2 on 2024-03-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_catalogpage_tab_delete_tabitem_delete_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogTabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(null=True)),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='games.catalogpage')),
            ],
            options={
                'verbose_name': 'Catalog Tab',
                'verbose_name_plural': 'Catalog Tabs',
                'db_table': 'catalog_tabs',
                'ordering': ['order'],
            },
        ),
    ]
