# Generated by Django 5.0.2 on 2024-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_catalogtabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarblock',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarblock',
            name='subtitle_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarblock',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarblock',
            name='title_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarblockitem',
            name='team1_img_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarblockitem',
            name='team1_img_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarblockitem',
            name='team2_img_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarblockitem',
            name='team2_img_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalogpage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='catalogpage',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='catalogpage',
            name='title_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='catalogpage',
            name='title_ua',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='catalogtabs',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='catalogtabs',
            name='content_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='catalogtabs',
            name='title_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='catalogtabs',
            name='title_ua',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='logo_filter_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='logo_filter_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='logo_product_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='logo_product_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worthlookitem',
            name='image_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worthlookitem',
            name='image_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
