# Generated by Django 5.0.2 on 2024-03-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_catalogpage_is_deleted_game_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogpage',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_pages', related_query_name='game', to='games.game'),
        ),
    ]
