# Generated by Django 5.0.2 on 2024-03-26 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_catalogpage_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogpage',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.calendar'),
        ),
        migrations.AlterField(
            model_name='catalogpage',
            name='worth_look',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.worthlook'),
        ),
    ]
