# Generated by Django 5.0.2 on 2024-03-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_team_remove_calendarblockitem_team1_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarblockitem',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars1', related_query_name='team1', to='games.team'),
        ),
        migrations.AddField(
            model_name='calendarblockitem',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars2', related_query_name='team2', to='games.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_img_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_img_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
