# Generated by Django 5.0.2 on 2024-02-26 21:03

import django.db.models.deletion
import src.website.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Select', 'Select'), ('Radio', 'Radio'), ('CheckBox', 'CheckBox')], max_length=50)),
            ],
            options={
                'verbose_name': 'Filters',
                'verbose_name_plural': 'Filters',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='SubFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.filter')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=src.website.utils.get_timestamp_path)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed'), ('range', 'Range')], max_length=10)),
                ('bonus_points', models.IntegerField(default=0)),
                ('sale', models.BooleanField()),
                ('sale_percent', models.PositiveSmallIntegerField()),
                ('sale_from', models.DateTimeField()),
                ('sale_until', models.DateTimeField()),
                ('runs', models.BooleanField()),
                ('price_per_run', models.FloatField()),
                ('bought_count', models.IntegerField()),
                ('catalog_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.catalogpage')),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.filter')),
                ('tab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tab')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.tag')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
