# -*- coding: utf-8 -*-
# Generated by Django 5.0.2 on 2024-03-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="type",
            field=models.CharField(
                choices=[("Select", "Select"), ("Radio", "Radio"), ("CheckBox", "CheckBox"), ("Slider", "Slider")],
                max_length=50,
            ),
        ),
    ]
