# Generated by Django 5.0.2 on 2024-04-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfilter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
