# -*- coding: utf-8 -*-
# Generated by Django 5.0.2 on 2024-04-01 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filter",
            old_name="title_ua",
            new_name="title_uk",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="card_img_alt_ua",
            new_name="card_img_alt_uk",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description_ua",
            new_name="description_uk",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="image_alt_ua",
            new_name="image_alt_uk",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="subtitle_ua",
            new_name="subtitle_uk",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title_ua",
            new_name="title_uk",
        ),
        migrations.RenameField(
            model_name="producttabs",
            old_name="content_ua",
            new_name="content_uk",
        ),
        migrations.RenameField(
            model_name="producttabs",
            old_name="title_ua",
            new_name="title_uk",
        ),
        migrations.RenameField(
            model_name="subfilter",
            old_name="title_ua",
            new_name="title_uk",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="name_ua",
            new_name="name_uk",
        ),
    ]
