# Generated by Django 5.0.2 on 2024-03-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttabs',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='products.product'),
        ),
    ]
