# Generated by Django 5.0.2 on 2024-04-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_subfilter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='freqbought',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
