# Generated by Django 5.0.2 on 2024-03-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_producttabs_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttabs',
            options={'ordering': ['order'], 'verbose_name': 'Product Tab', 'verbose_name_plural': 'Product Tabs'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='tab',
        ),
    ]
