# Generated by Django 5.0.2 on 2024-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_producttabs_options_remove_product_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='title_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='card_img_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='card_img_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttabs',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producttabs',
            name='content_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producttabs',
            name='title_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='producttabs',
            name='title_ua',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='subfilter',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subfilter',
            name='title_ua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
