# Generated by Django 5.0.2 on 2024-03-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_filter_title_en_filter_title_ua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
