# Generated by Django 5.0.2 on 2024-03-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
