# Generated by Django 5.0.2 on 2024-03-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_calendarblock_subtitle_en_calendarblock_subtitle_ua_and_more'),
        ('products', '0011_rename_deleted_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='games.catalogpage'),
        ),
    ]
