# Generated by Django 5.0.2 on 2024-03-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_catalogpage_is_deleted_game_is_deleted'),
        ('products', '0012_alter_product_catalog_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='games.catalogpage'),
        ),
    ]
