# Generated by Django 5.0.2 on 2024-03-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_catalogpage_game'),
        ('products', '0013_alter_product_catalog_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='games.catalogpage'),
        ),
    ]
