# Generated by Django 5.0.2 on 2024-03-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_tags_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreqBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(null=True)),
                ('discount', models.PositiveSmallIntegerField()),
                ('products', models.ManyToManyField(blank=True, related_name='products', to='products.product')),
            ],
            options={
                'verbose_name': 'Frequently Bought',
                'verbose_name_plural': 'Frequently Bought',
                'db_table': 'freq_bought',
            },
        ),
    ]
