# Generated by Django 5.0.2 on 2024-03-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_freqbought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freqbought',
            name='title',
        ),
    ]
