# Generated by Django 5.0.2 on 2024-03-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_freqbought_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='freqbought',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
