# Generated by Django 5.0.2 on 2024-03-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_freqbought_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freqbought',
            options={'ordering': ['order'], 'verbose_name': 'Frequently Bought', 'verbose_name_plural': 'Frequently Bought'},
        ),
    ]
