# Generated by Django 5.0.2 on 2024-03-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_freqbought_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freqbought',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='items', to='products.product'),
        ),
    ]
