# Generated by Django 5.0.2 on 2024-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_freqbought_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freqbought',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
