# Generated by Django 5.0.2 on 2024-03-30 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_freqbought_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('filters', models.ManyToManyField(blank=True, to='products.filter')),
            ],
            options={
                'verbose_name': 'Filter kit',
                'verbose_name_plural': 'Filter kits',
                'db_table': 'filter_kits',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='filter_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.filterkit'),
        ),
    ]
