# Generated by Django 5.0.2 on 2024-03-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_filterkit_product_filter_kit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filter_kit',
        ),
        migrations.DeleteModel(
            name='FilterKit',
        ),
    ]
