# Generated by Django 5.0.2 on 2024-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_sale_active',
            field=models.BooleanField(null=True),
        ),
    ]
