# -*- coding: utf-8 -*-
# Generated by Django 5.0.2 on 2024-04-05 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
