# Generated by Django 5.0.2 on 2024-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_subscribe_sale_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe_sale_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
