# -*- coding: utf-8 -*-
# Generated by Django 5.0.2 on 2024-03-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("in progress", "IN PROGRESS"), ("canceled", "CANCELED"), ("completed", "COMPLETED")],
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateField()),
                ("order_number", models.UUIDField(unique=True)),
                ("total_price", models.FloatField()),
            ],
            options={
                "verbose_name": "Orders",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sub_filter",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="products.subfilter"),
                ),
            ],
        ),
    ]
