# Generated by Django 5.0.2 on 2024-03-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'IN PROGRESS'), ('CANCELED', 'CANCELED'), ('COMPLETED', 'COMPLETED')], default='CANCELED', max_length=20),
        ),
    ]
