# Generated by Django 5.0.2 on 2024-04-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
    ]
