# Generated by Django 5.0.2 on 2024-04-19 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_promo_code'),
        ('products', '0003_alter_subfilter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFreqBotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('freqbot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.freqbought')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freqbot_items', to='orders.order')),
            ],
            options={
                'db_table': 'sub_freqbot_orders',
            },
        ),
    ]
