# Generated by Django 5.0.2 on 2024-03-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
