# Generated by Django 5.0.2 on 2024-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
    ]
