# Generated by Django 5.0.2 on 2024-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cartitem_product'),
        ('products', '0022_alter_freqbought_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='freqbought_items',
            field=models.ManyToManyField(blank=True, to='products.freqbought'),
        ),
    ]
