# Generated by Django 5.0.2 on 2024-04-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orderitem_freqbot'),
        ('orders', '0007_remove_order_freqbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.promocode'),
        ),
    ]
