# Generated by Django 5.0.2 on 2024-03-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cart_freqbought_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='freqbought_items',
        ),
    ]
