# Generated by Django 5.0.2 on 2024-03-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_cart_freqbought_items'),
        ('products', '0022_alter_freqbought_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='freqbot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.freqbought'),
        ),
    ]
