# Generated by Django 5.0.2 on 2024-03-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cartitem_freqbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='repeat_btn',
            field=models.BooleanField(default=True),
        ),
    ]
