# Generated by Django 5.0.2 on 2024-03-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_repeat_btn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='repeat_btn',
        ),
    ]
