# Generated by Django 5.0.2 on 2024-03-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_repeat_btn'),
        ('products', '0022_alter_freqbought_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='freqbot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.freqbought'),
        ),
    ]
