# Generated by Django 5.0.2 on 2024-03-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_freqbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_sale_active',
            field=models.BooleanField(default=False),
        ),
    ]
