# Generated by Django 5.0.2 on 2024-03-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_first_sale_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_sale_active',
        ),
    ]
