# Generated by Django 5.0.2 on 2024-03-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
    ]
