# Generated by Django 5.0.2 on 2024-02-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('until_date', models.DateField()),
                ('discount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Promo codes',
                'verbose_name_plural': 'Promo codes',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_nickname', models.CharField(max_length=255)),
                ('instagram_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('reddit_link', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('discord_link', models.URLField()),
                ('whats_up_link', models.URLField()),
                ('header_top_text', models.CharField(max_length=255)),
                ('footer_bottom_text', models.CharField(max_length=255)),
                ('footer_description', models.TextField()),
                ('privacy_policy_link', models.URLField()),
                ('terms_of_use_link', models.URLField()),
                ('refund_policy_link', models.URLField()),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('subscribe_form_text', models.CharField(max_length=255)),
                ('review_sale', models.PositiveSmallIntegerField()),
                ('subscribe_sale', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
