# Generated by Django 5.0.2 on 2024-02-26 21:03

import django.db.models.deletion
import src.website.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Insta',
                'verbose_name_plural': 'Insta',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('stars_count', models.PositiveSmallIntegerField()),
                ('source_of_review', models.CharField(max_length=255)),
                ('date_published', models.DateField()),
            ],
            options={
                'verbose_name': 'Reviews',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'WhyChooseUs',
                'verbose_name_plural': 'WhyChooseUs',
            },
        ),
        migrations.CreateModel(
            name='InstaImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=src.website.utils.get_timestamp_path)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='main.insta')),
            ],
            options={
                'verbose_name': 'Insta Imgs',
                'verbose_name_plural': 'Insta Imgs',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(null=True, upload_to=src.website.utils.get_timestamp_path)),
                ('description', models.TextField()),
                ('date_published', models.DateField(auto_now_add=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to=src.website.utils.get_timestamp_path)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.whychooseus')),
            ],
            options={
                'verbose_name': 'WhyChooseUs Item',
                'verbose_name_plural': 'WhyChooseUs Items',
            },
        ),
    ]
