# Generated by Django 5.0.2 on 2024-02-27 09:14

import src.website.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='insta',
            name='img',
            field=models.ImageField(null=True, upload_to=src.website.utils.get_timestamp_path),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='icon',
            field=models.ImageField(null=True, upload_to=src.website.utils.get_timestamp_path),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars_count',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='InstaImg',
        ),
        migrations.DeleteModel(
            name='WhyChooseUsItem',
        ),
    ]
