# -*- coding: utf-8 -*-
# Generated by Django 5.0.2 on 2024-04-01 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars_count",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
