# Generated by Django 5.0.2 on 2024-04-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_review_stars_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insta',
            old_name='img_alt_ua',
            new_name='img_alt_uk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image_alt_ua',
            new_name='image_alt_uk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_ua',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='orderitemattribute',
            old_name='title_ua',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author_ua',
            new_name='author_uk',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment_ua',
            new_name='comment_uk',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='address1_ua',
            new_name='address1_uk',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='address2_ua',
            new_name='address2_uk',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='footer_description_ua',
            new_name='footer_description_uk',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='header_top_text_ua',
            new_name='header_top_text_uk',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='subscribe_form_text_ua',
            new_name='subscribe_form_text_uk',
        ),
        migrations.RenameField(
            model_name='whychooseus',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='whychooseus',
            old_name='icon_alt_ua',
            new_name='icon_alt_uk',
        ),
        migrations.RenameField(
            model_name='whychooseus',
            old_name='title_ua',
            new_name='title_uk',
        ),
    ]
