# Generated by Django 5.0.2 on 2024-03-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='source_of_review_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
