# Generated by Django 5.0.2 on 2024-04-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_orderitem_cost'),
        ('products', '0003_alter_subfilter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='freqbot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.freqbought'),
        ),
    ]
