# Generated by Django 5.0.2 on 2024-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review_source_of_review_url_alter_whychooseus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='insta',
            name='img_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insta',
            name='img_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ua',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtitle_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='author_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='author_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address1_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address1_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address2_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address2_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='footer_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='footer_description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='header_top_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='header_top_text_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='subscribe_form_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='subscribe_form_text_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='icon_alt_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='icon_alt_ua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_ua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
