# Generated by Django 5.0.2 on 2024-04-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orderitem_freqbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemattribute',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitemattribute',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
