# Generated by Django 5.0.2 on 2024-04-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_orderitemattribute_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemattribute',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitemattribute',
            name='subtitle_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
