# Generated by Django 5.0.2 on 2024-03-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_insta_img_alt_en_insta_img_alt_ua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address1_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address2_link',
            field=models.URLField(null=True),
        ),
    ]
