# Generated by Django 5.0.2 on 2024-03-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_setting_address1_link_setting_address2_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subtitle_ua',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='title_ua',
        ),
    ]
