# Generated by Django 5.0.2 on 2024-03-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
