# Generated by Django 5.0.2 on 2024-03-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='subscribe_sale_active',
            field=models.BooleanField(default=True),
        ),
    ]
