# Generated by Django 5.0.2 on 2024-03-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_setting_subscribe_sale_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='subscribe_sale_active',
        ),
    ]
