# Generated by Django 5.0.2 on 2024-03-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_orderitemattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemattribute',
            name='title',
        ),
    ]
