# Generated by Django 5.0.2 on 2024-03-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_orderitemattribute_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemattribute',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitemattribute',
            name='title_ua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
